.TH CLIPDEL 1
.SH NAME
clipdel \- delete entries from the clip store
.SH SYNOPSIS
.B clipdel
[OPTION...] PATTERN
.SH DESCRIPTION
.B clipdel
removes clipboard entries from the clip store managed by clipmenu. By default,
it performs a dry-run and prints any matching entries. With the -d flag,
matching entries are permanently removed.
.SH OPTIONS
.TP
.B \-d
Real deletion mode. Matching clipboard entries will be removed.
.TP
.B \-F
Perform a literal (fixed-string) match instead of interpreting the pattern as a regular expression.
.TP
.B \-N
Interpret PATTERN as the amount of entries to delete starting from the oldest.
E.g
.I "\-N 1"
deletes the oldest entry.
.TP
.B \-n
Same as
.B \-N
but starting from newest.
.TP
.B \-v
Invert the matching condition; entries that do not match the given pattern are selected for deletion.
.TP
.B \-h, \--help
Display the help message (invokes the manual page).
.SH CONFIGURATION
See
.BR clipmenu.conf (5).
.SH DEPENDENCIES
clipdel requires access to the clip store directory as defined in the configuration.
.SH SEE ALSO
.BR clipctl (1),
.BR clipmenu (1),
.BR clipmenud (1),
.BR clipmenu.conf (5)
.SH AUTHOR
Chris Down
.MT chris@chrisdown.name
.ME
.SH REPORTING BUGS
Please send bug reports to
.UR https://github.com/cdown/clipmenu/issues
.UE .
