#!/usr/bin/env bash

# CLI for listing and retrieving clips

: "${CM_DIR="${XDG_RUNTIME_DIR-"${TMPDIR-/tmp}"}"}"

major_version=6

shopt -s nullglob

cache_dir=$CM_DIR/clipmenu.$major_version.$USER
cache_file=$cache_dir/line_cache

if ! [[ -f "$cache_file" ]]; then
    printf '%s\n' 'No cache file yet, did you run clipmenud?'
    exit 2
fi

print_help(){
    cat << 'EOF'
clipmenu is a simple clipboard manager using dmenu and xsel. Launch this
when you want to select a clip.
All arguments are passed through to dmenu itself.
Environment variables:
- $CM_DIR: specify the base directory to store the cache dir in (default: $XDG_RUNTIME_DIR, $TMPDIR, or /tmp)
EOF
    exit 0
}

list_clips() {
    LC_ALL=C sort -rnk 1 < "$cache_file" | cut -d' ' -f2- | awk '!seen[$0]++'
}

get_clip(){
    if [[ -n $1 ]]; then
        clip_line="$1"
    else
        read;
        clip_line="$REPLY"
    fi
    file=$cache_dir/$(cksum <<< "$clip_line")
    [[ -f "$file" ]] || exit 2
    cat "$file"
}

case "$1" in
    # Not -h, see #142
    -h|--help) print_help ;;
    list) list_clips; exit 0 ;;
    get) get_clip "$2"; exit 0 ;;
esac


