#!/usr/bin/env bash

# shellcheck disable=SC1091
source "${BASH_SOURCE[0]%/*}/setup.sh"

log="${tempdir?}/log"
tim="${tempdir}/tim"
num_files=1500

if ! (( NO_RECREATE )); then
    rm -rf "${dir?}"
fi

if ! [[ -d "${dir?}" ]]; then
    mkdir -p "$dir"
fi

num_need="$num_files"
for child in "$dir"/*; do
    if [[ -f "$child" ]] && ! [[ "$child" -ef "${cache_file?}" ]]; then
        (( num_need-- ))
    fi
done

if (( num_need > 0 )); then
    msg "Writing $num_need clipboard files"

    for (( i = 0; i <= num_need; i++ )); do
        (( i % 100 )) || printf '%s... ' "$i"

        line_len=$(( (RANDOM % 10000) + 1 ))
        num_lines=$(( (RANDOM % 10) + 1 ))
        data=$(
            tr -dc 'a-zA-Z0-9' < /dev/urandom |
                fold -w "$line_len" |
                head -"$num_lines"
        )
        read -r first_line_raw <<< "$data"
        printf -v first_line '%s (%s lines)\n' "$first_line_raw" "$num_lines"
        printf '%d %s' "$i" "$first_line" >> "${cache_file?}"
        fn=$dir/$(cksum <<< "$first_line")
        printf '%s' "$data" > "$fn"
    done

    printf 'done\n'
else
    msg 'Not nuking/creating new clipmenu files'
fi

msg 'Running clipmenu performance-testing wrapper'

time log="$log" tim="$tim" clipmenu-perf

(( TIME_ONLY )) && exit 0

msg 'Displaying perf data'

# modified from http://stackoverflow.com/a/20855353/945780
paste <(
    while read -r tim ;do
        [ -z "$last" ] && last=${tim//.} && first=${tim//.}
        crt=000000000$((${tim//.}-10#0$last))
        ctot=000000000$((${tim//.}-10#0$first))
        printf "%12.9f %12.9f\n" ${crt:0:${#crt}-9}.${crt:${#crt}-9} \
                                 ${ctot:0:${#ctot}-9}.${ctot:${#ctot}-9}
        last=${tim//.}
      done < "$tim"
) "$log" | less
